accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_page/<int:id>/',views.user_page, name="user_page"),
    path('follow/<int:id>/', views.follow, name="follow"),
    ]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/',include('accounts.urls')), # , 도 잊지마 은솔^^
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    # settings.AUTH_USER_MODEL -> User
    # 팔로우 하는사람들의 목록
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers",blank=True)
    
    def __str__(self):
        return self.username
        
    

posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=100)
    # image = models.ImageField(blank = True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # user를 변수화해서 넣음.
    # 1:N 관계(사용자 한명이 자기가 쓴 게시물을 여러개 가질 수 있다 -> on_delete=models.CASCADE 필요함)
    # 포스트랑 유저를 연결시킬 것!!
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set", blank=True)
        
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        upload_to = 'posts/images', # 저장위치
        processors = [ResizeToFill(600,600)], # 크기지정
        format = 'JPEG',
        options = {'quality':90},
        )
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # user한명이 comment 여러개 작성 가능
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
# class Like(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username','email',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
    else:
        form = CustomUserCreationForm()
    # 왜 return이 바깥쪽에 있을까?
    return render(request, 'accounts/form.html',{'form':form})
    
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request,"accounts/form.html",{'form':form})

def logout(request):
    auth_logout(request)
    return redirect("posts:list")

def user_page(request, id):
    User = get_user_model()
    user_info = User.objects.get(id=id)
    return render(request, "accounts/user_page.html",{'user_info':user_info})
    
def follow(request,id):
    User = get_user_model()
    me = request.user
    you = User.objects.get(id=id)
    
    # me:로그인한사람 you:팔로우버튼을 누른사람
    if me != you:
        if me in me.followings.all():
            me.followings.remove(you)
        else:
            me.followings.add(you)
    return redirect("accounts:user_page", id)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    {% if request.resolver_match.url_name == 'signup' %}
        <h1>회원가입</h1>
    {% else %}
        <h1>로그인</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" values="제출">
    </form>
   
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" values="제출">
    </form>
   
{% endblock %}

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}

{% block body %}
    <!--사용자 정보 출력 시작-->
    <div class="row">
        <div class="col-4">
            <!--프로필이미지-->
        </div>
        <div class="col-8">
            <!--유저 정보-->
            <h1>{{user_info.username}}</h1>
            {% if user != user_info %}
                {% if user_info in user.followings.all %}
                    <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-light">팔로잉</a>
                {% else %}
                    <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-primary">팔로우</a>
                {% endif %}
            {% endif %}
            <h5>팔로잉 : {{user_info.followings.count}}</h5>
            <h5>팔로워 : {{user_info.followers.count}}</h5>
        </div>
    </div>
    <!--사용자 정보 출력 끝-->
        <!--작성글 출력 시작-->
        <div class="card-columns">
            {% for post in user_info.post_set.all %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        </div>
    </div>
    <!--작성글 출력 끝-->
{% endblock %}