accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_page/<int:id>/',views.user_page, name="user_page"),
    path('follow/<int:id>/', views.follow, name="follow"),
    ]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/',include('accounts.urls')), # , 도 잊지마 은솔^^
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

# id가 있는 애들은 그 아이디에만 적용, 없으면 전체 적용
urlpatterns = [
    path('', views.list, name='list'),
    path('create/',views.create, name='create'),
    path('<int:id>/update/', views.update, name="update"),
    path('<int:id>/delete/', views.delete, name="delete"),
    
    path('<int:post_id>/comment/create/', views.comment_create, name="comment_create"),
    # path('<int:post_id>/comment/delete/', views.comment_delete, name="comment_delete"),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.comment_delete, name="comment_delete"),
    
    # 왜 create 안하나요? 
    path('<int:id>/like/', views.like, name="like"),
]

posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=100)
    # image = models.ImageField(blank = True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # user를 변수화해서 넣음.
    # 1:N 관계(사용자 한명이 자기가 쓴 게시물을 여러개 가질 수 있다 -> on_delete=models.CASCADE 필요함)
    # 포스트랑 유저를 연결시킬 것!!
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_post_set", blank=True)
        
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        upload_to = 'posts/images', # 저장위치
        processors = [ResizeToFill(600,600)], # 크기지정
        format = 'JPEG',
        options = {'quality':90},
        )
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # user한명이 comment 여러개 작성 가능
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    
# class Like(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

posts/forms.py
from django import forms
from .models import Post, Image, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ['content',] # content와 user의 정보를 다 보여주지 않고 content만
        
class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        # fields = '__all__'
        fields = ['file',]
        widgets = {
            'file' : forms.FileInput(attrs={'multiple':True})
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # fields = '__all__' # 입력을 받을 수 있도록 사용자에게 보여주는 곳    
        fields = ['content',] # content만 입력받으면 되기 때문에!!!!!!!!!!
    

posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, ImageForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

# Create your views here.
def list(request):
    posts = Post.objects.all()
    comment_form = CommentForm()
    return render(request, 'posts/list.html',{'posts':posts,'comment_form':comment_form})

@login_required
def create(request):
    # 1. get방식으로 데이터를 입력할 form을 요청한다.
    # 4. 사용자가 데이터를 입력해서 post방식으로 요청한다.
    # 9. 사용자가 다시 적절한 데이터를 입력해서 post방식으로 요청한다.
    if request.method == "POST": # 저장
        # 5. 10. post방식으로 저장요청을 받고, 데이터를 받아 PostForm에 넣어서 인스턴스화 한다.
        post_form = PostForm(request.POST)
        image_form = ImageForm(request.POST, request.FILES)
        # 6. 11. 데이터 검증을 한다.
        if post_form.is_valid():
            # 12. 적절한 데이터가 들어오는 경우, 데이터를 저장하고 list페이지로 리다이렉트!
            post = post_form.save(commit=False) # 저장이 된 게시물
            post.user = request.user
            post.save()
            for image in request.FILES.getlist('file'):
                request.FILES['file'] = image
                image_form = ImageForm(request.POST, request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False) # 잠깐만 기다려~~ 
                    image.post = post
                    image.save()
                    
            return redirect("posts:list")
        # else:
        #     # 7. 적절하지 않은 데이터가 들어오는 경우
        #     pass
    else: # get방식이면 폼을 보여줌
        # 2. PostForm을 인스턴스화 시켜서 form에 저장한다.
        post_form = PostForm()
        image_form = ImageForm()
    # 3. form을 담아서 create.html을 보내준다.
    # 8. 사용자가 입력한 데이터는 form에 담아진 상태로 다시 form을 담아서 create.html을 보내준다.
    return render(request, 'posts/form.html', {'post_form':post_form,'image_form':image_form})
  
@login_required
def update(request, id):
    # 게시물을 수정하려면 기존의 데이터 필요
    post = Post.objects.get(id=id)
    if post.user == request.user: # 지금 로그인한 사람이 게시물을 작성해따
            
        if request.method == "POST":
            post_form = PostForm(request.POST, instance=post) # create와 update는 instance=post 빼고는 구조가 같음.
            if post_form.is_valid():
                post_form.save()
                return redirect("posts:list")
        else:
            post_form = PostForm(instance=post)
        return render(request, 'posts/form.html',{'post_form':post_form})
    else:
        return redirect("posts:list")

@login_required
def delete(request,id):
    # 지우고싶은 게시물 찾고
    post = Post.objects.get(id=id)
    # 로그인한 유저랑 게시물작성 유저랑 같은지 확인
    if post.user == request.user:
        post.delete()
    return redirect("posts:list")


@login_required
@require_POST # comment_create가 POST방식이 아닐 땐 튕김.
def comment_create(request, post_id):
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = Post.objects.get(id=post_id)
            comment.save() # auto_now_add 를 이미 줘서 그냥 저장됨.
            return redirect("posts:list")
    
@login_required
def comment_delete(request, post_id, comment_id):
    # 코멘트 찾기
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()
    return redirect("posts:list")

# 이건 되는데 왜 되는지 모르게뜸
# @login_required
# def comment_delete(request, post_id):
#     comment = Comment.objects.get(id=post_id)
#     comment.delete()
#     return redirect("posts:list")

# 수정전코드
# @login_required
# def like(request):
#     user = request.user
#     post = Post.objects.get(id=id)
#     likes = post.like_set.all()
#     check = 0
#     for like in likes:
#         if user == like.user:
#             check = 1
#             like_post = like
#     if check == 1:
#         like_post.delete()
#     else:
#         like = Like(user=user, post=post)
#         like.save()
#     return redirect('posts:list')

@login_required
def like(request,id):
    # 현재 로그인한 사람의 정보
    user = request.user
    # 게시물
    post = Post.objects.get(id=id)
    # 사용자가 좋아요를 눌렀다면(사용자가 좋아요 목록에 있니?)
    if user in post.likes.all():
        post.likes.remove(user)
    # 사용자가 좋아요를 누르지 않았다면
    else:
        post.likes.add(user)
    return redirect('posts:list')

posts/templates/posts/_post.html
<div class="card my-5">
  <div class="card-header">
    <a href="{% url 'accounts:user_page' post.user.id %}" style="color:black"><h5 class="card-text">{{post.user}}</h5></a>
  </div>
  {% if post.image_set %}
    <div id="post{{post.id}}" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        {% for image in post.image_set.all %}
          <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
            <img src="{{image.file.url}}" class="d-block w-100" alt="...">
          </div>
        {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#post{{post.id}}" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#post{{post.id}}" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  {% else %}
    <img src="..." class="card-img-top" alt="...">
  {% endif %}
  
  <div class="card-body">
    <!--좋아요버튼시작-->
    {% if user in post.likes.all %}
    <!--지금 로그인한 유저가 이 게시물 좋아요를 눌렀니?-->
      <a href="{% url 'posts:like' post.id %}"><i class="fas fa-heart" style="color:#ed4956"></i></a>
    {% else %}
      <a href="{% url 'posts:like' post.id %}"><i class="far fa-heart" style="color:black"></i></a>
    {% endif %}
    <!--좋아요버튼끝-->
    <p class="card-text"><strong>{{post.user}}</strong>{{post.content}}</p>
    <p class="card-test">좋아요 {{post.likes.count}}개</p>
    <!--내가 작성한 게시물에만 수정, 삭제가 가능하게끔-->
    {% if post.user == user %}
      <!--몇번글을 수정하고 지울지?-->
      <a href="{% url 'posts:update' post.id %}" class="btn btn-warning">수정</a>
      <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">삭제</a>
    {% endif %}  
  </div>
  <!--댓글을 보여주는 부분-->
  <div class="card-body">
    {% for comment in post.comment_set.all %}
      <p class="card-text"><strong>{{comment.user}}</strong> {{comment.content}}</p>
      <!--삭제버튼-->
      {% if comment.user == user %}
        <a class="btn btn-danger" href="{% url 'posts:comment_delete' post.id comment.id %}">삭제</a>
      {% endif %}
    {% empty %}
      <!--내용이 없으면 실행됨-->
      <p class="card-text">!!!!무플방지!!!!</p>
    {% endfor %}
  </div>
  <!--댓글을 작성하는 공간-->
  <div class="card-body">
    <!--몇번글에 댓글을 달지?-->
    <form action="{% url 'posts:comment_create' post.id %}" method="post">
      {% csrf_token %}
      {{comment_form.content}}
      <input type="submit" value="제출"/>
    </form>
  </div>
</div>

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"/>
    </form>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method='post' enctype="multipart/form-data" accept="image/*">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        {% if image_form %}
            {% bootstrap_form image_form %}
        {% endif %}
        <input type="submit"/>
    </form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">
        <div class="col-6">
            {% for post in posts %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        </div>
    </div>

{% endblock %}